### YamlMime:ManagedReference
items:
- uid: Octopus.Client.AutomationEnvironments
  commentId: N:Octopus.Client.AutomationEnvironments
  id: Octopus.Client.AutomationEnvironments
  children:
  - Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  langs:
  - csharp
  - vb
  name: Octopus.Client.AutomationEnvironments
  nameWithType: Octopus.Client.AutomationEnvironments
  fullName: Octopus.Client.AutomationEnvironments
  type: Namespace
  assemblies:
  - Octopus.Client
references:
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  commentId: T:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  name: AutomationEnvironmentProvider
  nameWithType: AutomationEnvironmentProvider
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
