### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository
  commentId: T:Octopus.Client.Repositories.PerformanceConfigurationRepository
  id: PerformanceConfigurationRepository
  parent: Octopus.Client.Repositories
  children:
  - Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor(Octopus.Client.IOctopusRepository)
  - Octopus.Client.Repositories.PerformanceConfigurationRepository.Get
  - Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  langs:
  - csharp
  - vb
  name: PerformanceConfigurationRepository
  nameWithType: PerformanceConfigurationRepository
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository
  type: Class
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: PerformanceConfigurationRepository
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 10
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: 'public class PerformanceConfigurationRepository : IPerformanceConfigurationRepository'
    content.vb: >-
      Public Class PerformanceConfigurationRepository
          Implements IPerformanceConfigurationRepository
  inheritance:
  - System.Object
  implements:
  - Octopus.Client.Repositories.IPerformanceConfigurationRepository
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor(Octopus.Client.IOctopusRepository)
  commentId: M:Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor(Octopus.Client.IOctopusRepository)
  id: '#ctor(Octopus.Client.IOctopusRepository)'
  parent: Octopus.Client.Repositories.PerformanceConfigurationRepository
  langs:
  - csharp
  - vb
  name: PerformanceConfigurationRepository(IOctopusRepository)
  nameWithType: PerformanceConfigurationRepository.PerformanceConfigurationRepository(IOctopusRepository)
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.PerformanceConfigurationRepository(Octopus.Client.IOctopusRepository)
  type: Constructor
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: .ctor
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 14
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: public PerformanceConfigurationRepository(IOctopusRepository repository)
    parameters:
    - id: repository
      type: Octopus.Client.IOctopusRepository
    content.vb: Public Sub New(repository As IOctopusRepository)
  overload: Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.Get
  commentId: M:Octopus.Client.Repositories.PerformanceConfigurationRepository.Get
  id: Get
  parent: Octopus.Client.Repositories.PerformanceConfigurationRepository
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: PerformanceConfigurationRepository.Get()
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.Get()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Get
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 19
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: public PerformanceConfigurationResource Get()
    return:
      type: Octopus.Client.Model.PerformanceConfigurationResource
    content.vb: Public Function Get As PerformanceConfigurationResource
  overload: Octopus.Client.Repositories.PerformanceConfigurationRepository.Get*
  implements:
  - Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  commentId: M:Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  id: Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  parent: Octopus.Client.Repositories.PerformanceConfigurationRepository
  langs:
  - csharp
  - vb
  name: Modify(PerformanceConfigurationResource)
  nameWithType: PerformanceConfigurationRepository.Modify(PerformanceConfigurationResource)
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Modify
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 24
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: public PerformanceConfigurationResource Modify(PerformanceConfigurationResource resource)
    parameters:
    - id: resource
      type: Octopus.Client.Model.PerformanceConfigurationResource
    return:
      type: Octopus.Client.Model.PerformanceConfigurationResource
    content.vb: Public Function Modify(resource As PerformanceConfigurationResource) As PerformanceConfigurationResource
  overload: Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify*
  implements:
  - Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Octopus.Client.Repositories
  commentId: N:Octopus.Client.Repositories
  name: Octopus.Client.Repositories
  nameWithType: Octopus.Client.Repositories
  fullName: Octopus.Client.Repositories
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  commentId: T:Octopus.Client.Repositories.IPerformanceConfigurationRepository
  parent: Octopus.Client.Repositories
  name: IPerformanceConfigurationRepository
  nameWithType: IPerformanceConfigurationRepository
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor*
  commentId: Overload:Octopus.Client.Repositories.PerformanceConfigurationRepository.#ctor
  name: PerformanceConfigurationRepository
  nameWithType: PerformanceConfigurationRepository.PerformanceConfigurationRepository
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.PerformanceConfigurationRepository
- uid: Octopus.Client.IOctopusRepository
  commentId: T:Octopus.Client.IOctopusRepository
  parent: Octopus.Client
  name: IOctopusRepository
  nameWithType: IOctopusRepository
  fullName: Octopus.Client.IOctopusRepository
- uid: Octopus.Client
  commentId: N:Octopus.Client
  name: Octopus.Client
  nameWithType: Octopus.Client
  fullName: Octopus.Client
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.Get*
  commentId: Overload:Octopus.Client.Repositories.PerformanceConfigurationRepository.Get
  name: Get
  nameWithType: PerformanceConfigurationRepository.Get
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.Get
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  commentId: M:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  parent: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  name: Get()
  nameWithType: IPerformanceConfigurationRepository.Get()
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get()
  spec.csharp:
  - uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
    name: Get
    nameWithType: IPerformanceConfigurationRepository.Get
    fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
    name: Get
    nameWithType: IPerformanceConfigurationRepository.Get
    fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Octopus.Client.Model.PerformanceConfigurationResource
  commentId: T:Octopus.Client.Model.PerformanceConfigurationResource
  parent: Octopus.Client.Model
  name: PerformanceConfigurationResource
  nameWithType: PerformanceConfigurationResource
  fullName: Octopus.Client.Model.PerformanceConfigurationResource
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify*
  commentId: Overload:Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify
  name: Modify
  nameWithType: PerformanceConfigurationRepository.Modify
  fullName: Octopus.Client.Repositories.PerformanceConfigurationRepository.Modify
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  commentId: M:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  parent: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  name: Modify(PerformanceConfigurationResource)
  nameWithType: IPerformanceConfigurationRepository.Modify(PerformanceConfigurationResource)
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  spec.csharp:
  - uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
    name: Modify
    nameWithType: IPerformanceConfigurationRepository.Modify
    fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify
  - name: (
    nameWithType: (
    fullName: (
  - uid: Octopus.Client.Model.PerformanceConfigurationResource
    name: PerformanceConfigurationResource
    nameWithType: PerformanceConfigurationResource
    fullName: Octopus.Client.Model.PerformanceConfigurationResource
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
    name: Modify
    nameWithType: IPerformanceConfigurationRepository.Modify
    fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify
  - name: (
    nameWithType: (
    fullName: (
  - uid: Octopus.Client.Model.PerformanceConfigurationResource
    name: PerformanceConfigurationResource
    nameWithType: PerformanceConfigurationResource
    fullName: Octopus.Client.Model.PerformanceConfigurationResource
  - name: )
    nameWithType: )
    fullName: )
