### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Model.PersistenceSettingsType
  commentId: T:Octopus.Client.Model.PersistenceSettingsType
  id: PersistenceSettingsType
  parent: Octopus.Client.Model
  children:
  - Octopus.Client.Model.PersistenceSettingsType.Database
  - Octopus.Client.Model.PersistenceSettingsType.VersionControlled
  langs:
  - csharp
  - vb
  name: PersistenceSettingsType
  nameWithType: PersistenceSettingsType
  fullName: Octopus.Client.Model.PersistenceSettingsType
  type: Enum
  source:
    remote:
      path: source/Octopus.Client/Model/PersistenceSettings.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: PersistenceSettingsType
    path: ../source/Octopus.Client/Model/PersistenceSettings.cs
    startLine: 4
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public enum PersistenceSettingsType
    content.vb: Public Enum PersistenceSettingsType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Octopus.Client.Model.PersistenceSettingsType.Database
  commentId: F:Octopus.Client.Model.PersistenceSettingsType.Database
  id: Database
  parent: Octopus.Client.Model.PersistenceSettingsType
  langs:
  - csharp
  - vb
  name: Database
  nameWithType: PersistenceSettingsType.Database
  fullName: Octopus.Client.Model.PersistenceSettingsType.Database
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/PersistenceSettings.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Database
    path: ../source/Octopus.Client/Model/PersistenceSettings.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: Database = 0
    return:
      type: Octopus.Client.Model.PersistenceSettingsType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Octopus.Client.Model.PersistenceSettingsType.VersionControlled
  commentId: F:Octopus.Client.Model.PersistenceSettingsType.VersionControlled
  id: VersionControlled
  parent: Octopus.Client.Model.PersistenceSettingsType
  langs:
  - csharp
  - vb
  name: VersionControlled
  nameWithType: PersistenceSettingsType.VersionControlled
  fullName: Octopus.Client.Model.PersistenceSettingsType.VersionControlled
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/PersistenceSettings.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: VersionControlled
    path: ../source/Octopus.Client/Model/PersistenceSettings.cs
    startLine: 7
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: VersionControlled = 1
    return:
      type: Octopus.Client.Model.PersistenceSettingsType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Model.PersistenceSettingsType
  commentId: T:Octopus.Client.Model.PersistenceSettingsType
  parent: Octopus.Client.Model
  name: PersistenceSettingsType
  nameWithType: PersistenceSettingsType
  fullName: Octopus.Client.Model.PersistenceSettingsType
