### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Model.WebPortalConfigResource
  commentId: T:Octopus.Client.Model.WebPortalConfigResource
  id: WebPortalConfigResource
  parent: Octopus.Client.Model
  children:
  - Octopus.Client.Model.WebPortalConfigResource.#ctor
  - Octopus.Client.Model.WebPortalConfigResource.Id
  - Octopus.Client.Model.WebPortalConfigResource.Links
  - Octopus.Client.Model.WebPortalConfigResource.Security
  langs:
  - csharp
  - vb
  name: WebPortalConfigResource
  nameWithType: WebPortalConfigResource
  fullName: Octopus.Client.Model.WebPortalConfigResource
  type: Class
  source:
    remote:
      path: source/Octopus.Client/Model/WebPortalConfigurationResource.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: WebPortalConfigResource
    path: ../source/Octopus.Client/Model/WebPortalConfigurationResource.cs
    startLine: 7
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: 'public class WebPortalConfigResource : IResource'
    content.vb: >-
      Public Class WebPortalConfigResource
          Implements IResource
  inheritance:
  - System.Object
  implements:
  - Octopus.Client.Extensibility.IResource
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Octopus.Client.Model.WebPortalConfigResource.#ctor
  commentId: M:Octopus.Client.Model.WebPortalConfigResource.#ctor
  id: '#ctor'
  parent: Octopus.Client.Model.WebPortalConfigResource
  langs:
  - csharp
  - vb
  name: WebPortalConfigResource()
  nameWithType: WebPortalConfigResource.WebPortalConfigResource()
  fullName: Octopus.Client.Model.WebPortalConfigResource.WebPortalConfigResource()
  type: Constructor
  source:
    remote:
      path: source/Octopus.Client/Model/WebPortalConfigurationResource.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: .ctor
    path: ../source/Octopus.Client/Model/WebPortalConfigurationResource.cs
    startLine: 9
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public WebPortalConfigResource()
    content.vb: Public Sub New
  overload: Octopus.Client.Model.WebPortalConfigResource.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Octopus.Client.Model.WebPortalConfigResource.Id
  commentId: P:Octopus.Client.Model.WebPortalConfigResource.Id
  id: Id
  parent: Octopus.Client.Model.WebPortalConfigResource
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: WebPortalConfigResource.Id
  fullName: Octopus.Client.Model.WebPortalConfigResource.Id
  type: Property
  source:
    remote:
      path: source/Octopus.Client/Model/WebPortalConfigurationResource.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Id
    path: ../source/Octopus.Client/Model/WebPortalConfigurationResource.cs
    startLine: 14
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public string Id { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Id As String
  overload: Octopus.Client.Model.WebPortalConfigResource.Id*
  implements:
  - Octopus.Client.Extensibility.IResource.Id
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Octopus.Client.Model.WebPortalConfigResource.Links
  commentId: P:Octopus.Client.Model.WebPortalConfigResource.Links
  id: Links
  parent: Octopus.Client.Model.WebPortalConfigResource
  langs:
  - csharp
  - vb
  name: Links
  nameWithType: WebPortalConfigResource.Links
  fullName: Octopus.Client.Model.WebPortalConfigResource.Links
  type: Property
  source:
    remote:
      path: source/Octopus.Client/Model/WebPortalConfigurationResource.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Links
    path: ../source/Octopus.Client/Model/WebPortalConfigurationResource.cs
    startLine: 16
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public LinkCollection Links { get; set; }
    parameters: []
    return:
      type: Octopus.Client.Extensibility.LinkCollection
    content.vb: Public Property Links As LinkCollection
  overload: Octopus.Client.Model.WebPortalConfigResource.Links*
  implements:
  - Octopus.Client.Extensibility.IResource.Links
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Octopus.Client.Model.WebPortalConfigResource.Security
  commentId: P:Octopus.Client.Model.WebPortalConfigResource.Security
  id: Security
  parent: Octopus.Client.Model.WebPortalConfigResource
  langs:
  - csharp
  - vb
  name: Security
  nameWithType: WebPortalConfigResource.Security
  fullName: Octopus.Client.Model.WebPortalConfigResource.Security
  type: Property
  source:
    remote:
      path: source/Octopus.Client/Model/WebPortalConfigurationResource.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Security
    path: ../source/Octopus.Client/Model/WebPortalConfigurationResource.cs
    startLine: 21
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public WebPortalSecurityResource Security { get; set; }
    parameters: []
    return:
      type: Octopus.Client.Model.WebPortalSecurityResource
    content.vb: Public Property Security As WebPortalSecurityResource
  overload: Octopus.Client.Model.WebPortalConfigResource.Security*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Octopus.Client.Extensibility.IResource
  commentId: T:Octopus.Client.Extensibility.IResource
  parent: Octopus.Client.Extensibility
  name: IResource
  nameWithType: IResource
  fullName: Octopus.Client.Extensibility.IResource
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Octopus.Client.Extensibility
  commentId: N:Octopus.Client.Extensibility
  name: Octopus.Client.Extensibility
  nameWithType: Octopus.Client.Extensibility
  fullName: Octopus.Client.Extensibility
- uid: Octopus.Client.Model.WebPortalConfigResource.#ctor*
  commentId: Overload:Octopus.Client.Model.WebPortalConfigResource.#ctor
  name: WebPortalConfigResource
  nameWithType: WebPortalConfigResource.WebPortalConfigResource
  fullName: Octopus.Client.Model.WebPortalConfigResource.WebPortalConfigResource
- uid: Octopus.Client.Model.WebPortalConfigResource.Id*
  commentId: Overload:Octopus.Client.Model.WebPortalConfigResource.Id
  name: Id
  nameWithType: WebPortalConfigResource.Id
  fullName: Octopus.Client.Model.WebPortalConfigResource.Id
- uid: Octopus.Client.Extensibility.IResource.Id
  commentId: P:Octopus.Client.Extensibility.IResource.Id
  parent: Octopus.Client.Extensibility.IResource
  name: Id
  nameWithType: IResource.Id
  fullName: Octopus.Client.Extensibility.IResource.Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Octopus.Client.Model.WebPortalConfigResource.Links*
  commentId: Overload:Octopus.Client.Model.WebPortalConfigResource.Links
  name: Links
  nameWithType: WebPortalConfigResource.Links
  fullName: Octopus.Client.Model.WebPortalConfigResource.Links
- uid: Octopus.Client.Extensibility.IResource.Links
  commentId: P:Octopus.Client.Extensibility.IResource.Links
  parent: Octopus.Client.Extensibility.IResource
  name: Links
  nameWithType: IResource.Links
  fullName: Octopus.Client.Extensibility.IResource.Links
- uid: Octopus.Client.Extensibility.LinkCollection
  commentId: T:Octopus.Client.Extensibility.LinkCollection
  parent: Octopus.Client.Extensibility
  name: LinkCollection
  nameWithType: LinkCollection
  fullName: Octopus.Client.Extensibility.LinkCollection
- uid: Octopus.Client.Model.WebPortalConfigResource.Security*
  commentId: Overload:Octopus.Client.Model.WebPortalConfigResource.Security
  name: Security
  nameWithType: WebPortalConfigResource.Security
  fullName: Octopus.Client.Model.WebPortalConfigResource.Security
- uid: Octopus.Client.Model.WebPortalSecurityResource
  commentId: T:Octopus.Client.Model.WebPortalSecurityResource
  parent: Octopus.Client.Model
  name: WebPortalSecurityResource
  nameWithType: WebPortalSecurityResource
  fullName: Octopus.Client.Model.WebPortalSecurityResource
