### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  commentId: T:Octopus.Client.Repositories.IPerformanceConfigurationRepository
  id: IPerformanceConfigurationRepository
  parent: Octopus.Client.Repositories
  children:
  - Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  - Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  langs:
  - csharp
  - vb
  name: IPerformanceConfigurationRepository
  nameWithType: IPerformanceConfigurationRepository
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  type: Interface
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: IPerformanceConfigurationRepository
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 4
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: public interface IPerformanceConfigurationRepository
    content.vb: Public Interface IPerformanceConfigurationRepository
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  commentId: M:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  id: Get
  parent: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  langs:
  - csharp
  - vb
  name: Get()
  nameWithType: IPerformanceConfigurationRepository.Get()
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Get
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: PerformanceConfigurationResource Get()
    return:
      type: Octopus.Client.Model.PerformanceConfigurationResource
    content.vb: Function Get As PerformanceConfigurationResource
  overload: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get*
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  commentId: M:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  id: Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  parent: Octopus.Client.Repositories.IPerformanceConfigurationRepository
  langs:
  - csharp
  - vb
  name: Modify(PerformanceConfigurationResource)
  nameWithType: IPerformanceConfigurationRepository.Modify(PerformanceConfigurationResource)
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify(Octopus.Client.Model.PerformanceConfigurationResource)
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Modify
    path: ../source/Octopus.Client/Repositories/PerformanceConfigurationRepository.cs
    startLine: 7
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: PerformanceConfigurationResource Modify(PerformanceConfigurationResource resource)
    parameters:
    - id: resource
      type: Octopus.Client.Model.PerformanceConfigurationResource
    return:
      type: Octopus.Client.Model.PerformanceConfigurationResource
    content.vb: Function Modify(resource As PerformanceConfigurationResource) As PerformanceConfigurationResource
  overload: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify*
references:
- uid: Octopus.Client.Repositories
  commentId: N:Octopus.Client.Repositories
  name: Octopus.Client.Repositories
  nameWithType: Octopus.Client.Repositories
  fullName: Octopus.Client.Repositories
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get*
  commentId: Overload:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
  name: Get
  nameWithType: IPerformanceConfigurationRepository.Get
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Get
- uid: Octopus.Client.Model.PerformanceConfigurationResource
  commentId: T:Octopus.Client.Model.PerformanceConfigurationResource
  parent: Octopus.Client.Model
  name: PerformanceConfigurationResource
  nameWithType: PerformanceConfigurationResource
  fullName: Octopus.Client.Model.PerformanceConfigurationResource
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify*
  commentId: Overload:Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify
  name: Modify
  nameWithType: IPerformanceConfigurationRepository.Modify
  fullName: Octopus.Client.Repositories.IPerformanceConfigurationRepository.Modify
