### YamlMime:ManagedReference
items:
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  commentId: T:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  id: AutomationEnvironmentProvider
  parent: Octopus.Client.AutomationEnvironments
  children:
  - Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment
  - Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
  langs:
  - csharp
  - vb
  name: AutomationEnvironmentProvider
  nameWithType: AutomationEnvironmentProvider
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  type: Class
  source:
    remote:
      path: source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: AutomationEnvironmentProvider
    path: ../source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
    startLine: 9
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.AutomationEnvironments
  syntax:
    content: 'public class AutomationEnvironmentProvider : IAutomationEnvironmentProvider'
    content.vb: >-
      Public Class AutomationEnvironmentProvider
          Implements IAutomationEnvironmentProvider
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment
  commentId: M:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment
  id: DetermineAutomationEnvironment
  parent: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  langs:
  - csharp
  - vb
  name: DetermineAutomationEnvironment()
  nameWithType: AutomationEnvironmentProvider.DetermineAutomationEnvironment()
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: DetermineAutomationEnvironment
    path: ../source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
    startLine: 53
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.AutomationEnvironments
  syntax:
    content: public AutomationEnvironment DetermineAutomationEnvironment()
    return:
      type: Octopus.Client.Model.AutomationEnvironment
    content.vb: Public Function DetermineAutomationEnvironment As AutomationEnvironment
  overload: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
  commentId: M:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
  id: DetermineAutomationEnvironmentWithVersion
  parent: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider
  langs:
  - csharp
  - vb
  name: DetermineAutomationEnvironmentWithVersion()
  nameWithType: AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion()
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: DetermineAutomationEnvironmentWithVersion
    path: ../source/Octopus.Client/AutomationEnvironments/AutomationEnvironmentProvider.cs
    startLine: 58
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.AutomationEnvironments
  syntax:
    content: public string DetermineAutomationEnvironmentWithVersion()
    return:
      type: System.String
    content.vb: Public Function DetermineAutomationEnvironmentWithVersion As String
  overload: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Octopus.Client.AutomationEnvironments
  commentId: N:Octopus.Client.AutomationEnvironments
  name: Octopus.Client.AutomationEnvironments
  nameWithType: Octopus.Client.AutomationEnvironments
  fullName: Octopus.Client.AutomationEnvironments
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment*
  commentId: Overload:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment
  name: DetermineAutomationEnvironment
  nameWithType: AutomationEnvironmentProvider.DetermineAutomationEnvironment
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironment
- uid: Octopus.Client.Model.AutomationEnvironment
  commentId: T:Octopus.Client.Model.AutomationEnvironment
  parent: Octopus.Client.Model
  name: AutomationEnvironment
  nameWithType: AutomationEnvironment
  fullName: Octopus.Client.Model.AutomationEnvironment
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion*
  commentId: Overload:Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
  name: DetermineAutomationEnvironmentWithVersion
  nameWithType: AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
  fullName: Octopus.Client.AutomationEnvironments.AutomationEnvironmentProvider.DetermineAutomationEnvironmentWithVersion
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
