### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Repositories.Async.IConfigurationRepository
  commentId: T:Octopus.Client.Repositories.Async.IConfigurationRepository
  id: IConfigurationRepository
  parent: Octopus.Client.Repositories.Async
  children:
  - Octopus.Client.Repositories.Async.IConfigurationRepository.Get``1
  - Octopus.Client.Repositories.Async.IConfigurationRepository.Modify``1(``0)
  langs:
  - csharp
  - vb
  name: IConfigurationRepository
  nameWithType: IConfigurationRepository
  fullName: Octopus.Client.Repositories.Async.IConfigurationRepository
  type: Interface
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: IConfigurationRepository
    path: ../source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: public interface IConfigurationRepository
    content.vb: Public Interface IConfigurationRepository
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Octopus.Client.Repositories.Async.IConfigurationRepository.Get``1
  commentId: M:Octopus.Client.Repositories.Async.IConfigurationRepository.Get``1
  id: Get``1
  parent: Octopus.Client.Repositories.Async.IConfigurationRepository
  langs:
  - csharp
  - vb
  name: Get<T>()
  nameWithType: IConfigurationRepository.Get<T>()
  fullName: Octopus.Client.Repositories.Async.IConfigurationRepository.Get<T>()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Get
    path: ../source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
    startLine: 8
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: >-
      Task<T> Get<T>()
          where T : class, IResource, new()
    typeParameters:
    - id: T
    return:
      type: System.Threading.Tasks.Task{{T}}
    content.vb: Function Get(Of T As {Class, IResource, New}) As Task(Of T)
  overload: Octopus.Client.Repositories.Async.IConfigurationRepository.Get*
  nameWithType.vb: IConfigurationRepository.Get(Of T)()
  fullName.vb: Octopus.Client.Repositories.Async.IConfigurationRepository.Get(Of T)()
  name.vb: Get(Of T)()
- uid: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify``1(``0)
  commentId: M:Octopus.Client.Repositories.Async.IConfigurationRepository.Modify``1(``0)
  id: Modify``1(``0)
  parent: Octopus.Client.Repositories.Async.IConfigurationRepository
  langs:
  - csharp
  - vb
  name: Modify<T>(T)
  nameWithType: IConfigurationRepository.Modify<T>(T)
  fullName: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify<T>(T)
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Modify
    path: ../source/Octopus.Client/Repositories/Async/ConfigurationRepository.cs
    startLine: 9
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: >-
      Task<T> Modify<T>(T configurationResource)
          where T : class, IResource, new()
    parameters:
    - id: configurationResource
      type: '{T}'
    typeParameters:
    - id: T
    return:
      type: System.Threading.Tasks.Task{{T}}
    content.vb: Function Modify(Of T As {Class, IResource, New})(configurationResource As T) As Task(Of T)
  overload: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify*
  nameWithType.vb: IConfigurationRepository.Modify(Of T)(T)
  fullName.vb: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify(Of T)(T)
  name.vb: Modify(Of T)(T)
references:
- uid: Octopus.Client.Repositories.Async
  commentId: N:Octopus.Client.Repositories.Async
  name: Octopus.Client.Repositories.Async
  nameWithType: Octopus.Client.Repositories.Async
  fullName: Octopus.Client.Repositories.Async
- uid: Octopus.Client.Repositories.Async.IConfigurationRepository.Get*
  commentId: Overload:Octopus.Client.Repositories.Async.IConfigurationRepository.Get
  name: Get
  nameWithType: IConfigurationRepository.Get
  fullName: Octopus.Client.Repositories.Async.IConfigurationRepository.Get
- uid: System.Threading.Tasks.Task{{T}}
  commentId: T:System.Threading.Tasks.Task{``0}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<T>
  nameWithType: Task<T>
  fullName: System.Threading.Tasks.Task<T>
  nameWithType.vb: Task(Of T)
  fullName.vb: System.Threading.Tasks.Task(Of T)
  name.vb: Task(Of T)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify*
  commentId: Overload:Octopus.Client.Repositories.Async.IConfigurationRepository.Modify
  name: Modify
  nameWithType: IConfigurationRepository.Modify
  fullName: Octopus.Client.Repositories.Async.IConfigurationRepository.Modify
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: T
  name: T
  nameWithType: T
  fullName: T
