### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository
  commentId: T:Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository
  id: IFeaturesConfigurationRepository
  parent: Octopus.Client.Repositories.Async
  children:
  - Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  - Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  langs:
  - csharp
  - vb
  name: IFeaturesConfigurationRepository
  nameWithType: IFeaturesConfigurationRepository
  fullName: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository
  type: Interface
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: IFeaturesConfigurationRepository
    path: ../source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: public interface IFeaturesConfigurationRepository
    content.vb: Public Interface IFeaturesConfigurationRepository
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  commentId: M:Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  id: GetFeaturesConfiguration
  parent: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository
  langs:
  - csharp
  - vb
  name: GetFeaturesConfiguration()
  nameWithType: IFeaturesConfigurationRepository.GetFeaturesConfiguration()
  fullName: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: GetFeaturesConfiguration
    path: ../source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
    startLine: 8
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: Task<FeaturesConfigurationResource> GetFeaturesConfiguration()
    return:
      type: System.Threading.Tasks.Task{Octopus.Client.Model.FeaturesConfigurationResource}
    content.vb: Function GetFeaturesConfiguration As Task(Of FeaturesConfigurationResource)
  overload: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration*
- uid: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  commentId: M:Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  id: ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  parent: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository
  langs:
  - csharp
  - vb
  name: ModifyFeaturesConfiguration(FeaturesConfigurationResource)
  nameWithType: IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(FeaturesConfigurationResource)
  fullName: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: ModifyFeaturesConfiguration
    path: ../source/Octopus.Client/Repositories/Async/FeaturesConfigurationRepository.cs
    startLine: 9
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories.Async
  syntax:
    content: Task<FeaturesConfigurationResource> ModifyFeaturesConfiguration(FeaturesConfigurationResource resource)
    parameters:
    - id: resource
      type: Octopus.Client.Model.FeaturesConfigurationResource
    return:
      type: System.Threading.Tasks.Task{Octopus.Client.Model.FeaturesConfigurationResource}
    content.vb: Function ModifyFeaturesConfiguration(resource As FeaturesConfigurationResource) As Task(Of FeaturesConfigurationResource)
  overload: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration*
references:
- uid: Octopus.Client.Repositories.Async
  commentId: N:Octopus.Client.Repositories.Async
  name: Octopus.Client.Repositories.Async
  nameWithType: Octopus.Client.Repositories.Async
  fullName: Octopus.Client.Repositories.Async
- uid: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration*
  commentId: Overload:Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  name: GetFeaturesConfiguration
  nameWithType: IFeaturesConfigurationRepository.GetFeaturesConfiguration
  fullName: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.GetFeaturesConfiguration
- uid: System.Threading.Tasks.Task{Octopus.Client.Model.FeaturesConfigurationResource}
  commentId: T:System.Threading.Tasks.Task{Octopus.Client.Model.FeaturesConfigurationResource}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<FeaturesConfigurationResource>
  nameWithType: Task<FeaturesConfigurationResource>
  fullName: System.Threading.Tasks.Task<Octopus.Client.Model.FeaturesConfigurationResource>
  nameWithType.vb: Task(Of FeaturesConfigurationResource)
  fullName.vb: System.Threading.Tasks.Task(Of Octopus.Client.Model.FeaturesConfigurationResource)
  name.vb: Task(Of FeaturesConfigurationResource)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Octopus.Client.Model.FeaturesConfigurationResource
    name: FeaturesConfigurationResource
    nameWithType: FeaturesConfigurationResource
    fullName: Octopus.Client.Model.FeaturesConfigurationResource
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Octopus.Client.Model.FeaturesConfigurationResource
    name: FeaturesConfigurationResource
    nameWithType: FeaturesConfigurationResource
    fullName: Octopus.Client.Model.FeaturesConfigurationResource
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
- uid: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration*
  commentId: Overload:Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
  name: ModifyFeaturesConfiguration
  nameWithType: IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
  fullName: Octopus.Client.Repositories.Async.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
- uid: Octopus.Client.Model.FeaturesConfigurationResource
  commentId: T:Octopus.Client.Model.FeaturesConfigurationResource
  parent: Octopus.Client.Model
  name: FeaturesConfigurationResource
  nameWithType: FeaturesConfigurationResource
  fullName: Octopus.Client.Model.FeaturesConfigurationResource
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
