### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Repositories.IFeaturesConfigurationRepository
  commentId: T:Octopus.Client.Repositories.IFeaturesConfigurationRepository
  id: IFeaturesConfigurationRepository
  parent: Octopus.Client.Repositories
  children:
  - Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  - Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  langs:
  - csharp
  - vb
  name: IFeaturesConfigurationRepository
  nameWithType: IFeaturesConfigurationRepository
  fullName: Octopus.Client.Repositories.IFeaturesConfigurationRepository
  type: Interface
  source:
    remote:
      path: source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: IFeaturesConfigurationRepository
    path: ../source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
    startLine: 5
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: public interface IFeaturesConfigurationRepository
    content.vb: Public Interface IFeaturesConfigurationRepository
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  commentId: M:Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  id: GetFeaturesConfiguration
  parent: Octopus.Client.Repositories.IFeaturesConfigurationRepository
  langs:
  - csharp
  - vb
  name: GetFeaturesConfiguration()
  nameWithType: IFeaturesConfigurationRepository.GetFeaturesConfiguration()
  fullName: Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration()
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: GetFeaturesConfiguration
    path: ../source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
    startLine: 7
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: FeaturesConfigurationResource GetFeaturesConfiguration()
    return:
      type: Octopus.Client.Model.FeaturesConfigurationResource
    content.vb: Function GetFeaturesConfiguration As FeaturesConfigurationResource
  overload: Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration*
- uid: Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  commentId: M:Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  id: ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  parent: Octopus.Client.Repositories.IFeaturesConfigurationRepository
  langs:
  - csharp
  - vb
  name: ModifyFeaturesConfiguration(FeaturesConfigurationResource)
  nameWithType: IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(FeaturesConfigurationResource)
  fullName: Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration(Octopus.Client.Model.FeaturesConfigurationResource)
  type: Method
  source:
    remote:
      path: source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: ModifyFeaturesConfiguration
    path: ../source/Octopus.Client/Repositories/FeaturesConfigurationRepository.cs
    startLine: 8
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Repositories
  syntax:
    content: FeaturesConfigurationResource ModifyFeaturesConfiguration(FeaturesConfigurationResource resource)
    parameters:
    - id: resource
      type: Octopus.Client.Model.FeaturesConfigurationResource
    return:
      type: Octopus.Client.Model.FeaturesConfigurationResource
    content.vb: Function ModifyFeaturesConfiguration(resource As FeaturesConfigurationResource) As FeaturesConfigurationResource
  overload: Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration*
references:
- uid: Octopus.Client.Repositories
  commentId: N:Octopus.Client.Repositories
  name: Octopus.Client.Repositories
  nameWithType: Octopus.Client.Repositories
  fullName: Octopus.Client.Repositories
- uid: Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration*
  commentId: Overload:Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration
  name: GetFeaturesConfiguration
  nameWithType: IFeaturesConfigurationRepository.GetFeaturesConfiguration
  fullName: Octopus.Client.Repositories.IFeaturesConfigurationRepository.GetFeaturesConfiguration
- uid: Octopus.Client.Model.FeaturesConfigurationResource
  commentId: T:Octopus.Client.Model.FeaturesConfigurationResource
  parent: Octopus.Client.Model
  name: FeaturesConfigurationResource
  nameWithType: FeaturesConfigurationResource
  fullName: Octopus.Client.Model.FeaturesConfigurationResource
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration*
  commentId: Overload:Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
  name: ModifyFeaturesConfiguration
  nameWithType: IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
  fullName: Octopus.Client.Repositories.IFeaturesConfigurationRepository.ModifyFeaturesConfiguration
