### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  commentId: N:Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  id: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  children:
  - Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration.ExtensionConfigurationResource
  langs:
  - csharp
  - vb
  name: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  nameWithType: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  fullName: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration
  type: Namespace
  assemblies:
  - Octopus.Client
references:
- uid: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration.ExtensionConfigurationResource
  commentId: T:Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration.ExtensionConfigurationResource
  name: ExtensionConfigurationResource
  nameWithType: ExtensionConfigurationResource
  fullName: Octopus.Client.Extensibility.Extensions.Infrastructure.Configuration.ExtensionConfigurationResource
