### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Model.DeploymentProcess
  commentId: N:Octopus.Client.Model.DeploymentProcess
  id: Octopus.Client.Model.DeploymentProcess
  children:
  - Octopus.Client.Model.DeploymentProcess.InlineScriptAction
  - Octopus.Client.Model.DeploymentProcess.InlineScriptActionFromFileInAssembly
  - Octopus.Client.Model.DeploymentProcess.ScriptAction
  - Octopus.Client.Model.DeploymentProcess.ScriptActionFromFileInPackage
  - Octopus.Client.Model.DeploymentProcess.ScriptSource
  - Octopus.Client.Model.DeploymentProcess.ScriptTarget
  langs:
  - csharp
  - vb
  name: Octopus.Client.Model.DeploymentProcess
  nameWithType: Octopus.Client.Model.DeploymentProcess
  fullName: Octopus.Client.Model.DeploymentProcess
  type: Namespace
  assemblies:
  - Octopus.Client
references:
- uid: Octopus.Client.Model.DeploymentProcess.InlineScriptAction
  commentId: T:Octopus.Client.Model.DeploymentProcess.InlineScriptAction
  parent: Octopus.Client.Model.DeploymentProcess
  name: InlineScriptAction
  nameWithType: InlineScriptAction
  fullName: Octopus.Client.Model.DeploymentProcess.InlineScriptAction
- uid: Octopus.Client.Model.DeploymentProcess.InlineScriptActionFromFileInAssembly
  commentId: T:Octopus.Client.Model.DeploymentProcess.InlineScriptActionFromFileInAssembly
  parent: Octopus.Client.Model.DeploymentProcess
  name: InlineScriptActionFromFileInAssembly
  nameWithType: InlineScriptActionFromFileInAssembly
  fullName: Octopus.Client.Model.DeploymentProcess.InlineScriptActionFromFileInAssembly
- uid: Octopus.Client.Model.DeploymentProcess.ScriptAction
  commentId: T:Octopus.Client.Model.DeploymentProcess.ScriptAction
  parent: Octopus.Client.Model.DeploymentProcess
  name: ScriptAction
  nameWithType: ScriptAction
  fullName: Octopus.Client.Model.DeploymentProcess.ScriptAction
- uid: Octopus.Client.Model.DeploymentProcess.ScriptActionFromFileInPackage
  commentId: T:Octopus.Client.Model.DeploymentProcess.ScriptActionFromFileInPackage
  name: ScriptActionFromFileInPackage
  nameWithType: ScriptActionFromFileInPackage
  fullName: Octopus.Client.Model.DeploymentProcess.ScriptActionFromFileInPackage
- uid: Octopus.Client.Model.DeploymentProcess.ScriptSource
  commentId: T:Octopus.Client.Model.DeploymentProcess.ScriptSource
  parent: Octopus.Client.Model.DeploymentProcess
  name: ScriptSource
  nameWithType: ScriptSource
  fullName: Octopus.Client.Model.DeploymentProcess.ScriptSource
- uid: Octopus.Client.Model.DeploymentProcess.ScriptTarget
  commentId: T:Octopus.Client.Model.DeploymentProcess.ScriptTarget
  parent: Octopus.Client.Model.DeploymentProcess
  name: ScriptTarget
  nameWithType: ScriptTarget
  fullName: Octopus.Client.Model.DeploymentProcess.ScriptTarget
- uid: Octopus.Client.Model.DeploymentProcess
  commentId: N:Octopus.Client.Model.DeploymentProcess
  name: Octopus.Client.Model.DeploymentProcess
  nameWithType: Octopus.Client.Model.DeploymentProcess
  fullName: Octopus.Client.Model.DeploymentProcess
