### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Model.RunbookEnvironmentScope
  commentId: T:Octopus.Client.Model.RunbookEnvironmentScope
  id: RunbookEnvironmentScope
  parent: Octopus.Client.Model
  children:
  - Octopus.Client.Model.RunbookEnvironmentScope.All
  - Octopus.Client.Model.RunbookEnvironmentScope.FromProjectLifecycles
  - Octopus.Client.Model.RunbookEnvironmentScope.Specified
  langs:
  - csharp
  - vb
  name: RunbookEnvironmentScope
  nameWithType: RunbookEnvironmentScope
  fullName: Octopus.Client.Model.RunbookEnvironmentScope
  type: Enum
  source:
    remote:
      path: source/Octopus.Client/Model/RunbookEnvironmentScope.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: RunbookEnvironmentScope
    path: ../source/Octopus.Client/Model/RunbookEnvironmentScope.cs
    startLine: 2
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public enum RunbookEnvironmentScope
    content.vb: Public Enum RunbookEnvironmentScope
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Octopus.Client.Model.RunbookEnvironmentScope.All
  commentId: F:Octopus.Client.Model.RunbookEnvironmentScope.All
  id: All
  parent: Octopus.Client.Model.RunbookEnvironmentScope
  langs:
  - csharp
  - vb
  name: All
  nameWithType: RunbookEnvironmentScope.All
  fullName: Octopus.Client.Model.RunbookEnvironmentScope.All
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/RunbookEnvironmentScope.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: All
    path: ../source/Octopus.Client/Model/RunbookEnvironmentScope.cs
    startLine: 4
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: All = 0
    return:
      type: Octopus.Client.Model.RunbookEnvironmentScope
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Octopus.Client.Model.RunbookEnvironmentScope.Specified
  commentId: F:Octopus.Client.Model.RunbookEnvironmentScope.Specified
  id: Specified
  parent: Octopus.Client.Model.RunbookEnvironmentScope
  langs:
  - csharp
  - vb
  name: Specified
  nameWithType: RunbookEnvironmentScope.Specified
  fullName: Octopus.Client.Model.RunbookEnvironmentScope.Specified
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/RunbookEnvironmentScope.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: Specified
    path: ../source/Octopus.Client/Model/RunbookEnvironmentScope.cs
    startLine: 5
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: Specified = 1
    return:
      type: Octopus.Client.Model.RunbookEnvironmentScope
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Octopus.Client.Model.RunbookEnvironmentScope.FromProjectLifecycles
  commentId: F:Octopus.Client.Model.RunbookEnvironmentScope.FromProjectLifecycles
  id: FromProjectLifecycles
  parent: Octopus.Client.Model.RunbookEnvironmentScope
  langs:
  - csharp
  - vb
  name: FromProjectLifecycles
  nameWithType: RunbookEnvironmentScope.FromProjectLifecycles
  fullName: Octopus.Client.Model.RunbookEnvironmentScope.FromProjectLifecycles
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/RunbookEnvironmentScope.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: FromProjectLifecycles
    path: ../source/Octopus.Client/Model/RunbookEnvironmentScope.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: FromProjectLifecycles = 2
    return:
      type: Octopus.Client.Model.RunbookEnvironmentScope
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Model.RunbookEnvironmentScope
  commentId: T:Octopus.Client.Model.RunbookEnvironmentScope
  parent: Octopus.Client.Model
  name: RunbookEnvironmentScope
  nameWithType: RunbookEnvironmentScope
  fullName: Octopus.Client.Model.RunbookEnvironmentScope
