### YamlMime:ManagedReference
items:
- uid: Octopus.Client.Model.DeploymentStepPackageRequirement
  commentId: T:Octopus.Client.Model.DeploymentStepPackageRequirement
  id: DeploymentStepPackageRequirement
  parent: Octopus.Client.Model
  children:
  - Octopus.Client.Model.DeploymentStepPackageRequirement.AfterPackageAcquisition
  - Octopus.Client.Model.DeploymentStepPackageRequirement.BeforePackageAcquisition
  - Octopus.Client.Model.DeploymentStepPackageRequirement.LetOctopusDecide
  langs:
  - csharp
  - vb
  name: DeploymentStepPackageRequirement
  nameWithType: DeploymentStepPackageRequirement
  fullName: Octopus.Client.Model.DeploymentStepPackageRequirement
  type: Enum
  source:
    remote:
      path: source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: DeploymentStepPackageRequirement
    path: ../source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
    startLine: 2
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: public enum DeploymentStepPackageRequirement
    content.vb: Public Enum DeploymentStepPackageRequirement
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Octopus.Client.Model.DeploymentStepPackageRequirement.LetOctopusDecide
  commentId: F:Octopus.Client.Model.DeploymentStepPackageRequirement.LetOctopusDecide
  id: LetOctopusDecide
  parent: Octopus.Client.Model.DeploymentStepPackageRequirement
  langs:
  - csharp
  - vb
  name: LetOctopusDecide
  nameWithType: DeploymentStepPackageRequirement.LetOctopusDecide
  fullName: Octopus.Client.Model.DeploymentStepPackageRequirement.LetOctopusDecide
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: LetOctopusDecide
    path: ../source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
    startLine: 4
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: LetOctopusDecide = 0
    return:
      type: Octopus.Client.Model.DeploymentStepPackageRequirement
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Octopus.Client.Model.DeploymentStepPackageRequirement.BeforePackageAcquisition
  commentId: F:Octopus.Client.Model.DeploymentStepPackageRequirement.BeforePackageAcquisition
  id: BeforePackageAcquisition
  parent: Octopus.Client.Model.DeploymentStepPackageRequirement
  langs:
  - csharp
  - vb
  name: BeforePackageAcquisition
  nameWithType: DeploymentStepPackageRequirement.BeforePackageAcquisition
  fullName: Octopus.Client.Model.DeploymentStepPackageRequirement.BeforePackageAcquisition
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: BeforePackageAcquisition
    path: ../source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
    startLine: 5
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: BeforePackageAcquisition = 1
    return:
      type: Octopus.Client.Model.DeploymentStepPackageRequirement
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Octopus.Client.Model.DeploymentStepPackageRequirement.AfterPackageAcquisition
  commentId: F:Octopus.Client.Model.DeploymentStepPackageRequirement.AfterPackageAcquisition
  id: AfterPackageAcquisition
  parent: Octopus.Client.Model.DeploymentStepPackageRequirement
  langs:
  - csharp
  - vb
  name: AfterPackageAcquisition
  nameWithType: DeploymentStepPackageRequirement.AfterPackageAcquisition
  fullName: Octopus.Client.Model.DeploymentStepPackageRequirement.AfterPackageAcquisition
  type: Field
  source:
    remote:
      path: source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
      branch: docfx
      repo: https://github.com/pstephenson02/OctopusClients.git
    id: AfterPackageAcquisition
    path: ../source/Octopus.Client/Model/DeploymentStepPackageRequirement.cs
    startLine: 6
  assemblies:
  - Octopus.Client
  namespace: Octopus.Client.Model
  syntax:
    content: AfterPackageAcquisition = 2
    return:
      type: Octopus.Client.Model.DeploymentStepPackageRequirement
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Octopus.Client.Model
  commentId: N:Octopus.Client.Model
  name: Octopus.Client.Model
  nameWithType: Octopus.Client.Model
  fullName: Octopus.Client.Model
- uid: Octopus.Client.Model.DeploymentStepPackageRequirement
  commentId: T:Octopus.Client.Model.DeploymentStepPackageRequirement
  parent: Octopus.Client.Model
  name: DeploymentStepPackageRequirement
  nameWithType: DeploymentStepPackageRequirement
  fullName: Octopus.Client.Model.DeploymentStepPackageRequirement
